version = 0.1
[default.deploy.parameters]
stack_name = "rds-trigger-nuvola-coffee"
resolve_s3 = true
s3_prefix = "rds-trigger-nuvola-coffee"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
